server:
  servlet:
    context-path: /newsPusher
spring:
  datasource:
    username: username
    password: password
    url: jdbc:mysql:///newscrawl?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
mqtt:
  host:
    - tcp://:1883
  client-id: id
  username: username
  password: password
  keep-alive: 30
  max-inflight: 500
  clean-session: true
  timeout: 20000
  qos: 1
  async: false